export class Foodtruck {
  constructor(
    public id: string,
    public locationId: number,
    public applicant: string,
    public facilityType: string,
    public cnn: number,
    public locationDescription: string,
    public address: string,
    public blockLot: string,
    public block: string,
    public lot: string,
    public permit: string,
    public status: string,
    public foodItems: string,
    public x: number,
    public y: number,
    public latitude: number,
    public longitude: number,
    public schedule: string,
    public daysHours: string,
    public noiSent: string,
    public approved: string,
    public received: number,
    public priorPermit: number,
    public expirationDate: string,
    public location: string,
    public firePreventionDistricts: number,
    public policeDistricts: number,
    public supervisorDistricts: number,
    public zipCodes: number,
    public neighborhoodsOld: number,
  ) {}
}
